FROM python:3.9

WORKDIR /project

# Installing project requirements
RUN pip install scikit-learn pandas python-dotenv
RUN pip install mlrun

# Networking Utils
RUN apt update
RUN apt install net-tools iproute2 -y

ENTRYPOINT [ "bash" ]