name: Update Functions

on:
  workflow_dispatch:
    inputs:
      algorithm:
        required: false
        type: choice
        default: xg_boost
        options:
          - decision_tree_classifier
          - random_forest_classifier
          - xg_boost
          - light_gbm
          - mlp
      update-functions:
        type: bool
        required: false
        default: true
      update-pipelines:
        type: bool
        required: false
        default: true

jobs:
  update-functions:
    # Use self-hosted runner
    runs-on: self-hosted
    
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Update functions
      - name: Update Functions
        if: ${{ inputs.update-functions == true }}
        run: python update_functions.py 

      # Update Pipelines
      - name: Update Pipelines
        if: ${{ inputs.update-pipelines == 'true' }}
        run: python update_pipelines.py 