name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branch: 
      - ci-test

jobs:
  build:
    # Use self-hosted runner
    runs-on: self-hosted
    
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Run tests
      - name: Hello world
        run: |
          echo "Hello World! I'm a self hosted runner"
          ip a
          cd
          pwd

      # Install dependencies
      - name: Install dependencies
        run: docker run --rm --network host -v "$PWD":/project --name mlrun-dev mlrun-dev python update_functions.py

    

      # Build the project
      - name: Run function
        run: python update_functions.py    
