name: Update Functions

on:
  workflow_dispatch:
    inputs:
      Algorithm:
        required: false
        type: choice
        options:
          - decision_tree_classifier
          - random_forest_classifier
          - xg_boost
          - light_gbm
          - mlp
        default: xg_boost
      update-functions:
        type: bool
        required: false
        default: true
      update-pipelines:
        type: bool
        required: false
        default: true
        
  push:
    branch: 
      - ci-test

jobs:
  update-functions:
    # Use self-hosted runner
    runs-on: self-hosted
    
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Echo inputs
        run: |
          echo ${{ inputs.update-pipelines }}
          echo ${{ inputs.update-functions }}
          echo ${{ github.event.inputs.update-pipelines }}
      # Run tests
      - name: Lists content directories
        run: ls -la

      # Install dependencies
      - name: Install dependencies
        run: python update_functions.py 
