name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branch: 
      - ci-test

jobs:
  build:
    # Use self-hosted runner
    runs-on: self-hosted
    
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Run tests
      - name: Lists content directories
        run: ls -la

      # Install dependencies
      - name: Install dependencies
        run: python update_functions.py 
