name: Update Functions

on:
  workflow_dispatch:
    inputs:
      algorithm:
        required: false
        type: choice
        default: xg_boost
        options:
          - decision_tree_classifier
          - random_forest_classifier
          - xg_boost
          - light_gbm
          - mlp
      update-functions:
        type: bool
        required: false
        default: true
      update-pipelines:
        type: bool
        required: false
        default: true

jobs:
  update-functions:
    # Use self-hosted runner
    runs-on: self-hosted
    
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Echo inputs
        run: |
          echo ${{ inputs.update-pipelines }}
          echo ${{ inputs.update-functions }}
          echo ${{ inputs.algorithm }}
      # Run tests
      - name: Lists content directories
        run: ls -la

      
      - name: Update Functions
        if: ${{ inputs.update-functions == true }}
        run: python update_functions.py 
